name: Docker Workflows

on:
  push:
    branches:
      - main
      - jl/*
  pull_request:

jobs:
  # image-build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     # - name: "Set up Python"
  #     #   uses: actions/setup-python@v5
  #     #   with:
  #     #     python-version-file: "pyproject.toml"
  #     # - name: Install uv
  #     #   uses: astral-sh/setup-uv@v6
  #     #   with:
  #     #     enable-cache: true
  #     # - name: Install the project
  #     #   run: uv sync --locked --all-extras --dev

  #     # - name: Build tarxiv base image
  #     #   run: |
  #     #     cd setup
  #     #     docker compose build tarxiv-api

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: Dockerfile
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/tarxiv:${{ github.sha }} 
  #           ghcr.io/${{ github.repository_owner }}/tarxiv:latest

  compose-integration-tests:
    runs-on: ubuntu-latest
    # needs: image-build
    env:
      TARXIV_PORT: 9001
      TARXIV_IMAGE_SOURCE: local
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Setup compose environment
        run: |
          cd setup
          cp .env.sample .env
          mkdir -p .data/elastic .data/couchbase .data/redis
          chmod 777 .data/elastic .data/couchbase .data/redis
          ls -la .
          ls -la .data
          # docker compose up elasticsearch
          docker compose run setup_elasticsearch
          docker compose up -d elasticsearch logstash kibana couchbase
          sleep 60
      - name: Load test data
        run: |
          uv run --env-file setup/.env scripts/db_utils.py -l -f setup/example_dataset.json
      - name: Build tarxiv API image
        run: |
          # Build tarxiv image from local compose setup
          # TODO: should use the image built in the previous job
          cd setup
          docker compose build tarxiv-api
      - name: Start tarxiv API
        run: |
          cd setup
          docker compose up -d tarxiv-api
          sleep 20
          docker ps -a
          docker logs tarxiv-api
      - name: Start dashboard
        run: |
          cd setup
          docker compose up -d tarxiv-dashboard
          sleep 10
          docker ps -a
          docker logs tarxiv-dashboard
      - name: Ping API to check it's up
        run: |
          # This currently fails as the API startup is not working properly in CI 
          curl -f http://localhost:${{ env.TARXIV_PORT }}/ || exit 1
      - name: Teardown compose environment
        if: always()
        run: |
          cd setup
          docker inspect --format='{{.LogPath}}' setup-elasticsearch-1
          docker compose down -v
      - name : Save logs on failure
        if: failure()
        run: |
          cd setup
          docker compose logs > logs.txt
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tarxiv-logs
          path: setup/logs.txt
